### ISSUE TITLE
[특강] Docekr 실습 순서 공유

### ISSUE THREAD

**Issue by s-eunbi-kim** [eunbi-kim/24_2_W_SeProj#8]
# Docker 특강 실습 순서

### 1. Docker Desktip 설치 (Window)
* Window - WSL2 설치

### 2. Docker 사용
* 컨테이너 생성
* 이미지 생성 > 컨테이터 생성

### 3. Docekr-compose를 활용한 Jenkins 설치
* docker-compose.yml

### 4. Jenkins 설정
* Github Token 발급
* Jenkins <> Git 연결
* Maven 설정

### 5. Jenkins Job 생성
* Job 1 : git clone
* Job 2 : junit4 실행 / 정적 분석 Report

**Comment by s-eunbi-kim** [comment]
@jjoaa @YEJI-G-CHOI 안녕하세요~ 요청 주신 특강 강의 순서 공유 드립니다.
특강 때는 편의성을 위해 UI 환경을 설치하였지만, Docker Desktop 보다는 cmd에서 docker 사용을 더 많이 합니다. 

doc/99_etc/docker 기본 명령어.md
위의 파일에 기본 명령어를 정리해 놓았습니다. 
Docker 에 대해 더 공부하고 싶으시다면, 위의 파일을 참고하여 공부해 볼 것을 추천 드립니다~

**Comment by jjoaa** [comment]
선생님~
혹시 저희 우분투 리눅스 깔 때 비밀번호 설정했을까요?  
gcc 를 설치해야 하는데 비밀번호를 입력하라고 해서요ㅠ
<img width="330" alt="우분투" src="https://github.com/user-attachments/assets/be7899ea-1b42-4882-8494-7004ff0e9d31">

**Comment by s-eunbi-kim** [comment]
@jjoaa 넵 리눅스 비밀번호 설정했습니다.. wsl 설치하자 마자 바로 입력했었어요~ 
https://smiledk.tistory.com/11
비밀번호 분실하셨으면, 위의 url 참고하시면 재설정 가능합니다.
